# Site settings
title: hwije
description: Jekyll Theme Minimal Resume
# baseurl: "" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br
baseurl: ""
url: "https://hwije-jung.github.io/"
# User settings
username: 정휘제
user_description: 창원대학교 컴퓨터공학과의 빛 희망
user_title: SOFTWARE ENGINEER
email: gnlwp96@gmail.com
# twitter_username: lorem_ipsum
# github_username:  lorem_ipsum
# gplus_username:  lorem_ipsum

exclude: ['package.json', 'src' , 'node_modules']
